# Generated by Django 6.0.5 on 2026-08-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='academic_document',
            field=models.FileField(blank=True, null=True, upload_to='academic_docs/'),
        ),
        migrations.AddField(
            model_name='child',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
