# Generated by Django 6.0.5 on 2026-08-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_child_academic_document_child_previous_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='child_photos/'),
        ),
    ]
