# Generated by Django 6.0.5 on 2026-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_child_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='assigned_by',
            field=models.CharField(blank=True, default='Admin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerassignment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
