# Generated by Django 6.0.5 on 2026-09-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_child_aadhar_number_volunteer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
