# Generated by Django 6.0.5 on 2026-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_child_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian_relation',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Grandparent', 'Grandparent'), ('Sibling', 'Sibling'), ('Government', 'Government'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
