# Generated by Django 6.0.5 on 2026-09-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_child_guardian_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='areas_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='activity_type',
            field=models.CharField(blank=True, default='Education', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='assigned_children',
            field=models.CharField(blank=True, default='5 Children', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
