# Generated by Django 6.0.5 on 2026-09-30 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to='api.users'),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, default='Online Transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='purpose',
            field=models.CharField(blank=True, default='General Welfare', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='assignment_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='exam_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='internal_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_educations', to='api.users'),
        ),
        migrations.AddField(
            model_name='education',
            name='term',
            field=models.CharField(blank=True, default='Annual Exam', max_length=50),
        ),
        migrations.AddField(
            model_name='health',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_health_records', to='api.users'),
        ),
        migrations.AddField(
            model_name='health',
            name='doctor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='vaccination_status',
            field=models.CharField(blank=True, default='Up to Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('behaviour_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('behaviour_category', models.CharField(choices=[('Social', 'Social Interaction'), ('Emotional', 'Emotional Wellbeing'), ('Discipline', 'Discipline & Conduct'), ('Extracurricular', 'Extracurricular & Sports'), ('Academic', 'Academic Engagement')], default='Social', max_length=50)),
                ('incident_count', models.IntegerField(default=0)),
                ('interaction_score', models.DecimalField(decimal_places=1, default=8.0, max_digits=3)),
                ('participation_level', models.CharField(choices=[('High', 'High / Active Participation'), ('Medium', 'Moderate Participation'), ('Low', 'Needs Encouragement / Low')], default='High', max_length=50)),
                ('social_activities', models.TextField(blank=True, null=True)),
                ('extracurricular_activities', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('caregiver_remarks', models.TextField(blank=True, null=True)),
                ('recommended_intervention', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='api.child')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_behaviours', to='api.users')),
            ],
            options={
                'db_table': 'behaviour',
            },
        ),
    ]
