import random
from datetime import date, timedelta
from django.core.management.base import BaseCommand
from api.models import Child, HealthRecord, AcademicRecord, Donation, Volunteer


class Command(BaseCommand):
    help = 'Seeds the database with initial sample data'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding database...')

        # Clear existing data
        Child.objects.all().delete()
        Donation.objects.all().delete()
        Volunteer.objects.all().delete()

        # ── Children ──────────────────────────────────────────────
        names = [
            ('Arjun', 'Male'), ('Priya', 'Female'), ('Rahul', 'Male'),
            ('Anjali', 'Female'), ('Vikram', 'Male'), ('Sneha', 'Female'),
            ('Amit', 'Male'), ('Pooja', 'Female'), ('Suresh', 'Male'),
            ('Kavya', 'Female'), ('Rohit', 'Male'), ('Deepa', 'Female'),
        ]
        wings = ['Wing A', 'Wing B', 'Wing C', 'Wing D']
        statuses = ['Active', 'Active', 'Active', 'Inactive']

        children = []
        for i, (name, gender) in enumerate(names):
            age = random.randint(5, 16)
            c = Child.objects.create(
                name=name,
                age=age,
                gender=gender,
                wing=wings[i % 4],
                status=statuses[i % 4],
                enrollment_date=date.today() - timedelta(days=random.randint(30, 1000))
            )
            children.append(c)

            # Health record
            bmi = round(random.uniform(14.0, 28.0), 1)
            HealthRecord.objects.create(
                child=c,
                height=round(random.uniform(100, 170), 1),
                weight=round(random.uniform(20, 70), 1),
                bmi=bmi,
                blood_group=random.choice(['A+', 'B+', 'O+', 'AB+', 'A-', 'B-']),
                vaccination_status=random.choice(['Complete', 'Partial', 'Due']),
                sick_days=random.randint(0, 10),
                notes='Auto-generated by seed script.'
            )

            # Academic record
            AcademicRecord.objects.create(
                child=c,
                grade=f'Grade {random.randint(1, 10)}',
                math_score=random.randint(40, 100),
                science_score=random.randint(40, 100),
                english_score=random.randint(40, 100),
                attendance_rate=round(random.uniform(60.0, 100.0), 1),
                study_hours=random.randint(2, 20),
            )

        self.stdout.write(f'  Created {len(children)} children with health & academic records.')

        # ── Donations ─────────────────────────────────────────────
        donors = [
            ('Rajesh Kumar', 5000, 'Food & Nutrition'),
            ('Meera Sharma', 12000, 'Education'),
            ('Tech Corp Ltd', 50000, 'Infrastructure'),
            ('Anita Patel', 8000, 'Medical'),
            ('Global Trust', 30000, 'Clothing'),
            ('Sunil Verma', 3500, 'Food & Nutrition'),
        ]
        for i, (name, amount, category) in enumerate(donors):
            Donation.objects.create(
                donor_name=name,
                amount=amount,
                category=category,
                date=date.today() - timedelta(days=random.randint(0, 90)),
                receipt_id=f'RCP{2024000 + i}'
            )
        self.stdout.write(f'  Created {len(donors)} donations.')

        # ── Volunteers ────────────────────────────────────────────
        volunteers_data = [
            ('Dr. Ramesh Nair', 'ramesh@example.com', 'Medical, First Aid', 'Weekends', 120),
            ('Sunita Roy', 'sunita@example.com', 'Teaching, Arts & Crafts', 'Weekdays', 85),
            ('Arun Mehta', 'arun@example.com', 'Sports Coaching', 'Weekends', 60),
            ('Preethi Iyer', 'preethi@example.com', 'Counselling, Psychology', 'Flexible', 200),
            ('Kiran Bose', 'kiran@example.com', 'IT Support', 'Weekdays', 45),
        ]
        for name, email, skills, avail, hours in volunteers_data:
            Volunteer.objects.create(
                name=name, email=email, skills=skills,
                availability=avail, logged_hours=hours, status='Active'
            )
        self.stdout.write(f'  Created {len(volunteers_data)} volunteers.')

        self.stdout.write(self.style.SUCCESS('Database seeded successfully!'))
